const FETCH_SEARCHED_BOOKS = "FETCH_SEARCHED_BOOKS"
const SET_LOADING = "SET_LOADING"
const ADD_BOOK_LIST = "ADD_BOOK_LIST"
const ADD_BOOK_LIST_ERROR = "ADD_BOOK_LIST_ERROR"
const ADD_BOOK = "ADD_BOOK"
const ADD_BOOK_LIST_BOOK = "ADD_BOOK_LIST_BOOK"
const ADD_BOOK_LIST_BOOK_ERROR = "ADD_BOOK_LIST_BOOK_ERROR"
const REMOVE_BOOK_LIST_BOOK = "REMOVE_BOOK_LIST_BOOK"
const REMOVE_BOOK_LIST = "REMOVE_BOOK_LIST"
const SET_CURRENT_USER = "SET_CURRENT_USER"
const LOG_OUT = "LOG_OUT"
const LOG_IN_ERROR = "LOG_IN_ERROR"
const SIGN_UP_ERROR = "SIGN_UP_ERROR"
const PLEASE_LOG_IN = "PLEASE_LOG_IN"
const FETCH_USERS = "FETCH_USERS"
const FETCH_BOOK = "FETCH_BOOK"
const FETCH_BOOK_CLUBS = "FETCH_BOOK_CLUBS"
const ADD_BOOK_CLUB = "ADD_BOOK_CLUB"
const ADD_BOOK_CLUB_ERROR = "ADD_BOOK_CLUB_ERROR"
const REMOVE_BOOK_CLUB = "REMOVE_BOOK_CLUB"
const RECEIVE_MESSAGE = "RECEIVE_MESSAGE"
const MESSAGE_ERROR = "MESSAGE_ERROR"

export {
    FETCH_SEARCHED_BOOKS,
    SET_LOADING,
    ADD_BOOK_LIST,
    ADD_BOOK_LIST_ERROR,
    ADD_BOOK,
    ADD_BOOK_LIST_BOOK,
    ADD_BOOK_LIST_BOOK_ERROR,
    REMOVE_BOOK_LIST_BOOK,
    REMOVE_BOOK_LIST,
    SET_CURRENT_USER,
    LOG_OUT,
    LOG_IN_ERROR,
    SIGN_UP_ERROR,
    PLEASE_LOG_IN,
    FETCH_USERS,
    FETCH_BOOK,
    FETCH_BOOK_CLUBS,
    ADD_BOOK_CLUB,
    ADD_BOOK_CLUB_ERROR,
    REMOVE_BOOK_CLUB,
    RECEIVE_MESSAGE,
    MESSAGE_ERROR
}