const FETCH_SEARCHED_BOOKS = "FETCH_SEARCHED_BOOKS"
const ADD_BOOK_LIST = "ADD_BOOK_LIST"
const SET_CURRENT_USER = "SET_CURRENT_USER"
const LOG_OUT = "LOG_OUT"

export {
    FETCH_SEARCHED_BOOKS,
    ADD_BOOK_LIST,
    SET_CURRENT_USER,
    LOG_OUT
}