const FETCH_SEARCHED_BOOKS = "FETCH_SEARCHED_BOOKS"
const SET_LOADING = "SET_LOADING"
const ADD_BOOK_LIST = "ADD_BOOK_LIST"
const ADD_BOOK = "ADD_BOOK"
const ADD_BOOK_LIST_BOOK = "ADD_BOOK_LIST_BOOK"
const REMOVE_BOOK_LIST_BOOK = "REMOVE_BOOK_LIST_BOOK"
const REMOVE_BOOK_LIST = "REMOVE_BOOK_LIST"
const SET_CURRENT_USER = "SET_CURRENT_USER"
const LOG_OUT = "LOG_OUT"
const LOGIN_ERROR = "LOGIN_ERROR"
const FETCH_USERS = "FETCH_USERS"
const FETCH_BOOK = "FETCH_BOOK"
const FETCH_BOOK_CLUBS = "FETCH_BOOK_CLUBS"
const ADD_BOOK_CLUB = "ADD_BOOK_CLUB"
const REMOVE_BOOK_CLUB = "REMOVE_BOOK_CLUB"
const RECEIVE_MESSAGE = "RECEIVE_MESSAGE"

export {
    FETCH_SEARCHED_BOOKS,
    SET_LOADING,
    ADD_BOOK_LIST,
    ADD_BOOK,
    ADD_BOOK_LIST_BOOK,
    REMOVE_BOOK_LIST_BOOK,
    REMOVE_BOOK_LIST,
    SET_CURRENT_USER,
    LOG_OUT,
    LOGIN_ERROR,
    FETCH_USERS,
    FETCH_BOOK,
    FETCH_BOOK_CLUBS,
    ADD_BOOK_CLUB,
    REMOVE_BOOK_CLUB,
    RECEIVE_MESSAGE
}