const FETCH_SEARCHED_BOOKS = "FETCH_SEARCHED_BOOKS"
const SET_LOADING = "SET_LOADING"
const ADD_BOOK_LIST = "ADD_BOOK_LIST"
const ADD_BOOK = "ADD_BOOK"
const ADD_BOOK_LIST_BOOK = "ADD_BOOK_LIST_BOOK"
const REMOVE_BOOK_LIST_BOOK = "REMOVE_BOOK_LIST_BOOK"
const REMOVE_BOOK_LIST = "REMOVE_BOOK_LIST"
const SET_CURRENT_USER = "SET_CURRENT_USER"
const LOG_OUT = "LOG_OUT"
const FETCH_USERS = "FETCH_USERS"

export {
    FETCH_SEARCHED_BOOKS,
    SET_LOADING,
    ADD_BOOK_LIST,
    ADD_BOOK,
    ADD_BOOK_LIST_BOOK,
    REMOVE_BOOK_LIST_BOOK,
    REMOVE_BOOK_LIST,
    SET_CURRENT_USER,
    LOG_OUT,
    FETCH_USERS
}